org.gradle.jvmargs=-Xmx3G -Xms512m -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=true
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.118
neo_version_range=[21.1.0,)
loader_version_range=[1,)
pack_format_number=34
java_version=21
mod_version=0.1.5
mod_id=kunjinkao
mod_name=锟斤拷烫烫烫
mod_license=MIT
mod_authors=ModMind
mod_description=一把伤害超高的剑——锟斤拷（NeoForge 1.21.1 独立工程）
maven_group=dev.modmind.kunjinkao
archives_base_name=kunjinkao_neoforge_1.21.1
