modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.kunjinkao]]
modId="neoforge"
mandatory=true
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.kunjinkao]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
# 给 neoecoae 的兼容补丁（配置标了 required=false，没装那个模组时静默跳过）
[[mixins]]
config="kunjinkao.mixins.json"
